DROP DATABASE IF EXISTS Games_db;
CREATE DATABASE Games_db;

USE Games_db;

CREATE TABLE Users (
    ID INT NOT NULL  AUTO_INCREMENT PRIMARY KEY,
    Person_Name VARCHAR(100) NOT NULL,
    Username VARCHAR(100) NOT NULL,
    Password VARCHAR(100) NOT NULL,
    Active BIT DEFAULT (0),
    DateAdded DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Games (
    ID INT NOT NULL  AUTO_INCREMENT PRIMARY KEY,
    GameName VARCHAR(100),
    GameType VARCHAR(100),
    GameVersion VARCHAR(100);
    Platform VARCHAR(500);
    DateAdded DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE UserGames (
    ID INT NOT NULL  AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE SET NULL,
    FOREIGN KEY (GamesID) REFERENCES Games(ID) ON DELETE SET NULL
);